apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.namePrefix }}-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "operator.leaderElectionRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.fullname" . }}
