apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: benchmarks-client
  namespace: nos-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: benchmarks-client
  podMetricsEndpoints:
    - port: prometheus
  namespaceSelector:
    any: true
