apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dgcm-exporter
  namespace: nos-monitoring
spec:
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  endpoints:
    - port: gpu-metrics