/*
 * Copyright 2023 nebuly.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DevicePluginClient is an autogenerated mock type for the DevicePluginClient type
type DevicePluginClient struct {
	mock.Mock
}

// Restart provides a mock function with given fields: ctx, nodeName, timeout
func (_m *DevicePluginClient) Restart(ctx context.Context, nodeName string, timeout time.Duration) error {
	ret := _m.Called(ctx, nodeName, timeout)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, nodeName, timeout)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDevicePluginClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewDevicePluginClient creates a new instance of DevicePluginClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDevicePluginClient(t mockConstructorTestingTNewDevicePluginClient) *DevicePluginClient {
	mock := &DevicePluginClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
